### ISSUE TITLE
after latest mesa update rendering is software only

### ISSUE THREAD

**Issue by phush0** [WhitewaterFoundry/Fedora-Remix-for-WSL#213]
update from 23.1.9 to 23.2.1 lead to llvmpipe only rendering and no hardware acceleration

**Comment by crramirez** [comment]
Yes you cannot upgrade mesa by yourself because the upstream one doesn't include D3D12. We compile each mesa version that we ship with Fedora to include the Direct3D 12 support. Sometimes is impossible and we need to lock the version.

Run the `update.sh`. It will download the right version and put the version locks to avoid the version get updated again by accident.

**Comment by phush0** [comment]
installing dnf5 will break version lock just to be aware
