### ISSUE TITLE
Fedora 30 ?

### ISSUE THREAD

**Issue by fathonir** [WhitewaterFoundry/Fedora-Remix-for-WSL#37]
As I've seen the announcement of Fedora 30 today (https://fedoramagazine.org/announcing-fedora-30/), when we will recieves the updates soon in fedora-remix ?

**Comment by tkatz77** [comment]
I was able to perform a manual upgrade using the dnf system-upgrade plugin.  It wasn't completely straight forward since you can't actually perform a reboot.  I had to edit/replace the /etc/os-release file when done, and clear the ("hidden") lock files out of /var/lib/rpm.

Things seem to still work, however I really only use WSL for a bunch of cli tools so I'm not sure what, if anything, is broken.  I did (appear to) break the system a few times trying to upgrade, so if this is attempted I would back up the installation first (I used lxrunoffline to export to a tgz and used that to create separate installs to test with).

An official way to upgrade would be nice.

**Comment by fathonir** [comment]
> I was able to perform a manual upgrade using the dnf system-upgrade plugin.  It wasn't completely straight forward since you can't actually perform a reboot.  I had to edit/replace the /etc/os-release file when done, and clear the ("hidden") lock files out of /var/lib/rpm.
> Things seem to still work, however I really only use WSL for a bunch of cli tools so I'm not sure what, if anything, is broken.  I did (appear to) break the system a few times trying to upgrade, so if this is attempted I would back up the installation first (I used lxrunoffline to export to a tgz and used that to create separate installs to test with).
> An official way to upgrade would be nice.

@tkatz77 I don't think to take a risk to perform manually upgrade like that. The configurations that I've been set for the environment may have to re-set if it something problem happened. So, agree with you, official way is the best choice 😅



> This is not a running linux system with processes and kernel, so there is no need for system-upgrade. You can simply run:
> sudo dnf upgrade --releasever=30
> Restart the console and you are good to go.
> (Sometimes I've had "dnf upgrade" processes stuck for some reason. It is solved by removing the rpm lock file in /var/lib/rpm/. This is not something that happens on Linux, so it must be a WSL feature).

@setupdev Thanks, i will try this method.

**Comment by fathonir** [comment]
I've done performing upgrade by using this command :
`sudo dnf upgrade --releasever=30`
and everything works well.

Thanks @setupdev :)

**Comment by sirredbeard** [comment]
We will be releasing a new build in the Store from Fedora 30 in the next couple weeks. So far no reports of issues.

**Comment by srl295** [comment]
installed from https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases/download/1.30.1/DistroLauncher-Appx_1.30.1.0_x64.appx ( thanks, this works well!) .. it's clearly fedora 30 (at least after usual updates) but /etc/os-release still says 29.
