### ISSUE TITLE
versioning question

### ISSUE THREAD

**Issue by jacksnodgrass** [WhitewaterFoundry/Fedora-Remix-for-WSL#85]
on: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases - the versions went from: 
1.31.21 Final 
to
31.5.0

is there a significance in the 1.31.x to 31.5.x jump? Is it because the 31.5 is not  Final.. a dev build maybe? 

Is your versioning detailed anywhere? 

- jack

**Comment by crramirez** [comment]
Hello Jack,

The version scheme change is explained here: https://www.whitewaterfoundry.com/blog/2020/4/8/whitewater-foundry-version-scheme-change

Fedora Remix for WSL:
This distribution is wholly tied to Fedora mainstream release. The logic says that we should number it according to the Fedora version, which it is based.  So the version numbers now will be: FEDORA_RELEASE.MM.##, and the next release will be 31.04.0.

It is not a big change. We didn't include the Final in the version name due to a mistake.

Regards,
Carlos
